[programs.testnet]
example1 = "7CiTJHXzv7SdK1bf14nmCnPg9c8HRs3H9DdfEJMoay5K"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "testnet"
wallet = "config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
